This is an internal working file generated by the Source Browser.
15:45 58s
D:\FEIBIT CC2530\BasicRF实验及源程序\CC2530 BasicRF\CC2530 BasicRF\source\Components\targets\srf05_soc\hal_led.c
D:\FEIBIT CC2530\BasicRF实验及源程序\CC2530 BasicRF\CC2530 BasicRF\source\Components\targets\srf05_soc\hal_led.c
-D
chip=2530
-D
INCLUDE_PA=2591
--diag_suppress
Pe001,Pa084
-o
D:\FEIBIT CC2530\BasicRF实验及源程序\CC2530 BasicRF\CC2530 BasicRF\ide\srf05_cc2530_91\iar\temp\per_test\
-e
--no_code_motion
--debug
--core=plain
--dptr=16,1
--data_model=large
--code_model=near
--calling_convention=xdata_reentrant
--place_constants=data
--nr_virtual_regs
8
-I
D:\FEIBIT CC2530\BasicRF实验及源程序\CC2530 BasicRF\CC2530 BasicRF\ide\srf05_cc2530_91\iar/../../../source/Components/utils\
-I
D:\FEIBIT CC2530\BasicRF实验及源程序\CC2530 BasicRF\CC2530 BasicRF\ide\srf05_cc2530_91\iar/../../../source/Components/common\
-I
D:\FEIBIT CC2530\BasicRF实验及源程序\CC2530 BasicRF\CC2530 BasicRF\ide\srf05_cc2530_91\iar/../../../source/Components/basicrf\
-I
D:\FEIBIT CC2530\BasicRF实验及源程序\CC2530 BasicRF\CC2530 BasicRF\ide\srf05_cc2530_91\iar/../../../source/Components/targets/interface\
-I
D:\FEIBIT CC2530\BasicRF实验及源程序\CC2530 BasicRF\CC2530 BasicRF\ide\srf05_cc2530_91\iar/../../../source/Components/assembly\
-I
D:\FEIBIT CC2530\BasicRF实验及源程序\CC2530 BasicRF\CC2530 BasicRF\ide\srf05_cc2530_91\iar/../../../source/Components/common/cc8051\
-I
D:\FEIBIT CC2530\BasicRF实验及源程序\CC2530 BasicRF\CC2530 BasicRF\ide\srf05_cc2530_91\iar/../../../source/Components/targets/srf05_soc\
-I
D:\FEIBIT CC2530\BasicRF实验及源程序\CC2530 BasicRF\CC2530 BasicRF\ide\srf05_cc2530_91\iar/../../../source/Components/radios/cc2530\
-I
C:\Program Files\IAR Systems\Embedded Workbench 5.3\8051\INC\
-I
C:\Program Files\IAR Systems\Embedded Workbench 5.3\8051\INC\CLIB\
-Ohz
